Name: ModifyFile001
Description: Test ModifyFile (ConfigFile) Handler
Actions:
- Name: ConfigFile
  Handler:
    Type: Synapse.Handlers.FileUtil:ModifyFileHandler
    Config:
      Type: Yaml
      Values:
        Type : KeyValue
        BackupSource: true
        CreateSettingIfNotFound: true
        RunSequential: true
        Aws:
          AccessKey: xxxxxxxx
          SecretKey: xxxxxxxx
          Region: eu-west-1
  Parameters:
    Type: Yaml
    Values:
      Files:
      - Source: C:\Temp\javainput.properties
        Destination: C:\Temp\javaoutput.properties
        SettingsFile: 
          Name: C:\Temp\kvptransform.csv
        Settings:
        - Key: baseGroup.ABCDEFG-svrMessageLogger.isLogging
          Value: false
      - Source: s3://mybucket/FileMunge/javainput.properties
        Destination: s3://mybucket/FileMunge/output/javaoutput.properties
        SettingsFile: 
          Name: s3://mybucket/FileMunge/kvptransform.csv
        Settings:
        - Key: baseGroup.ABCDEFG-svrMessageLogger.isLogging
          Value: false