Name: ModifyFile001
Description: Test ModifyFile (ConfigFile) Handler
Actions:
- Name: ConfigFile
  Handler:
    Type: Synapse.Handlers.FileUtil:MungeFileHandler
    Config:
      Type: Yaml
      Values:
        Type : XmlTransform
        BackupSource: true
        CreateSettingIfNotFound: true
        RunSequential: true
        OverwriteExisting: true
        Aws:
          AccessKey: xxxxxxxx
          SecretKey: xxxxxxxx
          Region: eu-west-1
  Parameters:
    Type: Yaml
    Values:
      Files:
      - Source: C:\Temp\Web.config
        Destination: C:\Temp\Web.config.new
        OverwriteExisting: false
        SettingsFile: 
          Name: C:\Temp\Web.NEW.
      - Source: s3://mybucket/FileMunge/Web.config
        Destination: s3://mybucket/FileMunge/output/Web.config.new
        SettingsFile: 
          Name: s3://mybucket/FileMunge/Web.NEW.config
          HasEncryptedValues: false
