Name: ModifyFile001
Description: Test ModifyFile (ConfigFile) Handler
Actions:
- Name: ConfigFile
  Handler:
    Type: Synapse.Handlers.FileUtil:ModifyFileHandler
    Config:
      Type: Yaml
      Values:
        Type : INI
        BackupSource: true
        CreateSettingIfNotFound: true
        RunSequential: true
        Aws:
          AccessKey: xxxxxxxx
          SecretKey: xxxxxxxx
          Region: eu-west-1
  Parameters:
    Type: Yaml
    Values:
      Files:
      - Source: C:\Temp\input.ini
        Destination: C:\Temp\output.ini
        SettingsFile: 
          Name: C:\Temp\initransform.csv
        Settings:
        - Key: TESTKEY
          Value: Guy Waguespack Was Here
        - Key: "[ODBC 32 bit Data Sources]:TESTKEY"
          Value: Guy Waguespack Was Here Too
      - Source: s3://mybucket/FileMunge/input.ini
        Destination: s3://mybucket/FileMunge/output/output.ini
        SettingsFile: 
          Name: s3://mybucket/FileMunge/initransform.csv
          HasEncryptedValues: true
        Settings:
        - Key: TESTKEY
          Value: Guy Waguespack Was Here
        - Key: "[ODBC 32 bit Data Sources]:TESTKEY"
          Value: Guy Waguespack Was Here Too
    Crypto:
      Key:
        Uri: C:\Synapse\Keys\SynapseDev-PublicPrivate.key
        ContainerName: SynapseDev