Name: QueryService
Description: Test WinCore Handler
IsActive: true
Actions:
- Name: SimpleServiceQuery
  Handler:
    Type: Synapse.Handlers.Legacy.StandardCopyProcess:StandardCopyProcessHandler
  Parameters:
    Type: Xml
    Values: 
      <StandardCopy>
        <DeploymentRoot>C:\Temp</DeploymentRoot>
        <Servers>
          <Server>localhost</Server>
        </Servers>
        <SourceDirectory>Source</SourceDirectory>
        <TargetServerDestination>C:\Temp\Destination</TargetServerDestination>
        <ConfigFiles>
          <ConfigFile TransformFile="EmptyFileXform.xml">EmptyFile.txt</ConfigFile>
        </ConfigFiles>
      </StandardCopy>
