Name: Simple Copy
Description: Test Simple Copy
IsActive: true
Actions:
- Name: SimpleCopy
  Handler:
    Type: Synapse.Handlers.Legacy.StandardCopyProcess:StandardCopyProcessHandler
    Config:
      Type: Yaml
      Values:
        Aws:
#          AccessKey: xxxxxxxxxxxxxxxxxxxx
#          SecretKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          Region: eu-west-1
  Parameters:
    Type: Xml
    Values: 
      <StandardCopy>
        <SourceDirectory>C:\Temp\Source</SourceDirectory>
        <TargetRemoteDestination>\\localhost\c$\Temp\Remote</TargetRemoteDestination>
        <ConfigFiles>
          <ConfigFile TransformFile="web.xform.config" TransformInPlace="false">web.config</ConfigFile>
        </ConfigFiles>
      </StandardCopy>